/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AvailablePlanksTable: typeof import('./components/AvailablePlanksTable.vue')['default']
    ComputeStatusBar: typeof import('./components/ComputeStatusBar.vue')['default']
    CutPlanView: typeof import('./components/CutPlanView.vue')['default']
    GlobalSettingsCard: typeof import('./components/GlobalSettingsCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PlankVisualization: typeof import('./components/PlankVisualization.vue')['default']
    PurchasePlanTable: typeof import('./components/PurchasePlanTable.vue')['default']
    RequiredPiecesTable: typeof import('./components/RequiredPiecesTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
